services:
  - type: static_site
    name: minegestion-dash
    rootDir: frontend
    env:
      NODE_VERSION: 20.19.0
    buildCommand: "npm cache clean --force && npm install --legacy-peer-deps --verbose && npm run build"
    publishPath: "build"
