services:
  - type: static_site
    name: minegestion-dash
    rootDir: frontend
    buildCommand: "npm cache clean --force && npm install --legacy-peer-deps && npm run build"
    publishPath: "build"
    cache: false
